### ISSUE TITLE
blockscout integration

### ISSUE THREAD

**Issue by 0x677261706562616261** [b2network/cdk-validium-node#10]
Check if blockscout supported polygon zkrollup

[here](https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/commit/dc12f6ae2b2fb13689339aa1b7ad76d4ba007398) seems exist a demo

**Comment by oxf71** [comment]
Find two associated branches and try to build from source

https://github.com/blockscout/blockscout/tree/va-zkevm
https://github.com/blockscout/frontend/tree/zkevm-batches

**Comment by 0x677261706562616261** [comment]
> Find two associated branches and try to build from source
> 
> https://github.com/blockscout/blockscout/tree/va-zkevm https://github.com/blockscout/frontend/tree/zkevm-batches

ok, but may need deep investigation, it seems blockscout not use branch to track different chain

**Comment by oxf71** [comment]
blockscout works successfully using the built-in front end of the master branch, but can only display transactions on L1 normally, and cannot display transactions after L2

next
1. [x] build a docker image on the zkevm branch and check whether the transactions on L2 can be displayed normally
2. [x] Use the new blockscout redesign to build  docker image on the zkevm branch and check whether the transactions on L2 can be displayed normally


explorer L1

<img width="1620" alt="截屏2023-10-20 14 34 03" src="https://github.com/b2network/cdk-validium-node/assets/144757737/f0fbb636-c36f-41c5-af47-3989f22872a1">

explorer L2


<img width="1571" alt="截屏2023-10-20 14 35 05" src="https://github.com/b2network/cdk-validium-node/assets/144757737/0160e8d9-64d7-4dd6-ad76-b992eee97624">

**Comment by oxf71** [comment]
By build zkevm branch docker image, transactions on L2 can be displayed normally

<img width="1550" alt="截屏2023-10-20 17 12 58" src="https://github.com/b2network/cdk-validium-node/assets/144757737/cca50aef-222f-437d-a922-5346888b4f33">

**Comment by oxf71** [comment]
## Description
An error occurs using the official blockscout-zkevm branch

error log:
```
explorer-l2  | init terminating in do_boot ({,[{Elixir.Code,find_file!,2,[{_},{_}]},{Elixir.Code,eval_file,2,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{elixir,eval_forms,4,[{_},{_}]},{Elixir.Module.ParallelChecker,verify,1,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]}]})
explorer-l2  |
explorer-l2  | Crash dump is being written to: erl_crash.dump...done
explorer-l2  | ERROR! Config provider Config.Reader failed with:
explorer-l2  | ** (Code.LoadError) could not load /app/releases/5.3.0/config_helper.exs. Reason: enoent
explorer-l2  |     (elixir 1.14.5) lib/code.ex:1826: Code.find_file!/2
explorer-l2  |     (elixir 1.14.5) lib/code.ex:1199: Code.eval_file/2
explorer-l2  |     (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
explorer-l2  |     (stdlib 3.17) erl_eval.erl:123: :erl_eval.exprs/5
explorer-l2  |     (elixir 1.14.5) src/elixir.erl:297: :elixir.eval_forms/4
explorer-l2  |     (elixir 1.14.5) lib/module/parallel_checker.ex:110: Module.ParallelChecker.verify/1
explorer-l2  |     (elixir 1.14.5) lib/code.ex:425: Code.validated_eval_string/3
explorer-l2  |     (elixir 1.14.5) lib/config.ex:288: Config.__eval__!/3
explorer-l2  |
explorer-l2  | {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Code.LoadError',file=><<"/app/releases/5.3.0/config_helper.exs">>,message=><<"could not load /app/releases/5.3.0/config_helper.exs. Reason: enoent">>,reason=>enoent},[{'Elixir.Code','find_file!',2,[{file,"lib/code.ex"},{line,1826}]},{'Elixir.Code',eval_file,2,[{file,"lib/code.ex"},{line,1199}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},{elixir,eval_forms,4,[{file,"src/elixir.erl"},{line,297}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,110}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,425}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,288}]}]}}
explorer-l2  | init terminating in do_boot ({,[{Elixir.Code,find_file!,2,[{_},{_}]},{Elixir.Code,eval_file,2,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{elixir,eval_forms,4,[{_},{_}]},{Elixir.Module.ParallelChecker,verify,1,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]}]})
explorer-l2  |
explorer-l2  | Crash dump is being written to: erl_crash.dump...done
explorer-l2 exited with code 1
```

## Version
image: blockscout/blockscout-zkevm:latest
image id: c4d21765799d

docker-compose config:

```
  explorer-l2:
    depends_on:
      - db2
    image: blockscout/blockscout-zkevm:latest
    restart: always
    container_name: 'explorer-l2'
    # links:
    #   - db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./envs/common-explorer-l2.env
    environment:
      NETWORK: 'POE'
      SUBNETWORK: 'B2network l2'
      COIN: 'ETH'
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      # BLOCK_TRANSFORMER: 'clique'
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8124/
      DATABASE_URL: postgres://postgres:postgres@db2:5432/test_db?ssl=false
      ECTO_USE_SSL: 'false'
      SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
      API_V2_ENABLED: 'true'
    ports:
      - 4006:4000
```
